#!/usr/bin/env python3
"""
compare_flows.py  –  GEM Deliverable A Verification
Compares the two synthesis output netlists:
  1. gatelevel_baseline.gv   : CARRY4 shredded into AIG gates (Original GEM)
  2. gatelevel_macropreserve.gv : CARRY4 preserved intact    (Modified GEM, Deliverable A)
"""

import re
import sys
import os

BASELINE_GV = "test1/flowA_gatelevel_baseline.gv"
PRESERVE_GV = "test1/flowB_gatelevel_macropreserve.gv"


def count_cells(filepath):
    """Returns a dict of {cell_type: count} from a gatelevel Verilog file."""
    counts = {}
    with open(filepath) as f:
        for line in f:
            # Match instantiations like: AND2_00_0 _19_ (
            m = re.match(r'\s+(\w+)\s+\w+\s+\(', line)
            if m:
                cell = m.group(1)
                counts[cell] = counts.get(cell, 0) + 1
    return counts

def has_carry4(filepath):
    with open(filepath) as f:
        content = f.read()
    return bool(re.search(r'\bCARRY4\b', content))

def print_cell_table(label, counts):
    print(f"\n  {label}")
    print(f"  {'Cell Type':<20} {'Count':>6}")
    total = 0
    for cell, n in sorted(counts.items()):
        print(f"  {cell:<20} {n:>6}")
        total += n
    print(f"  {'TOTAL':<20} {total:>6}")
    return total

def main():
    print("  GEM DELIVERABLE A  —  Macro Preservation Verification")
    print("  Test Circuit: AND gate + OR gate + XOR gate + CARRY4 macro")

    for path in [BASELINE_GV, PRESERVE_GV]:
        if not os.path.exists(path):
            print(f"\n[ERROR] File not found: {path}")
            print("  Please run both Yosys scripts first:")
            sys.exit(1)

    base_cells = count_cells(BASELINE_GV)
    pres_cells = count_cells(PRESERVE_GV)

    base_total = print_cell_table("FLOW A — Original GEM (CARRY4 SHREDDED into AIG cells)", base_cells)
    pres_total = print_cell_table("FLOW B — Modified GEM (CARRY4 PRESERVED, Deliverable A)", pres_cells)

    print()
    print("  COMPARISON SUMMARY")

    # CARRY4 check
    base_has_c4 = has_carry4(BASELINE_GV)
    pres_has_c4 = has_carry4(PRESERVE_GV)

    carry4_baseline_status = "ABSENT  (shredded into logic - PASS)"   if not base_has_c4 else "PRESENT (not shredded!) - FAIL"
    carry4_preserve_status = "PRESENT (intact — PASS)"         if pres_has_c4     else "ABSENT  (FAIL!)"

    print(f"\n  CARRY4 in baseline netlist  : {carry4_baseline_status}")
    print(f"  CARRY4 in preserve netlist  : {carry4_preserve_status}")

    # Gate count comparison
    non_carry4_pres = {k: v for k, v in pres_cells.items() if k != "CARRY4"}
    non_carry4_total = sum(non_carry4_pres.values())

    print(f"\n  Total cells  — Flow A (shredded)  : {base_total}")
    print(f"  Total cells  — Flow B (preserved)  : {pres_total}")
    print(f"  AIG gates only — Flow B (excl CARRY4) : {non_carry4_total}")
    print(f"  Gates saved by preserving CARRY4  : {base_total - pres_total} fewer cells in netlist")

    # Cell types only in baseline (came from CARRY4 internals)
    carry4_aig_cells = {k: v for k, v in base_cells.items() if k not in pres_cells or base_cells[k] > pres_cells.get(k, 0)}

    print(f"\n  AIG cells generated by shredding CARRY4 (extra in Flow A):")
    for cell, bcount in sorted(base_cells.items()):
        pcount = pres_cells.get(cell, 0)
        if bcount > pcount:
            print(f"    {cell:<24} +{bcount - pcount}")

    print()
    print("  VERDICT")

    if pres_has_c4 and not base_has_c4:
        print("""
  [PASS] Deliverable A CONFIRMED:

  Flow A (Original GEM):
    - Reads CARRY4 as a transparent module
    - synth/abc/techmap see inside it
    - Replaces all CARRY4 logic with AND2_xx_x + INV AIG cells
    - CARRY4 is completely absent from output netlist

  Flow B (Modified GEM — Deliverable A):
    - Reads CARRY4 via aigpdk/aigpdk_macros_bb.v as a blackbox
    - synth/abc/techmap cannot see inside it
    - CARRY4 survives all optimization passes unchanged
    - Output netlist contains CARRY4 u_carry4 ( ... ) intact
    - Only the surrounding AND/OR/XOR logic is mapped to AIG cells
""")
    else:
        print("\n  [FAIL] Expected CARRY4 to be absent from baseline and present in preserve.")


if __name__ == "__main__":
    main()

