/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

(* top =  1  *)
(* src = "test0/half_adder.sv:2.1-12.10" *)
module half_adder(A, B, Sum, Carry);
  (* src = "test0/half_adder.sv:3.12-3.13" *)
  input A;
  wire A;
  (* src = "test0/half_adder.sv:4.12-4.13" *)
  input B;
  wire B;
  (* src = "test0/half_adder.sv:5.12-5.15" *)
  output Sum;
  wire Sum;
  (* src = "test0/half_adder.sv:6.12-6.17" *)
  output Carry;
  wire Carry;
  assign Carry = A & (* src = "test0/half_adder.sv:10.20-10.25" *) B;
  assign Sum = A ^ (* src = "test0/half_adder.sv:9.20-9.25" *) B;
endmodule
